NGLS-3202 Superset: Add indicator that download is in progress
GCL-UCC-NG911/superset pull request #15
Opened 2023-07-21 10:55 UTC by EduardoSanday

After the user clicks on options to download the dashboard, a message will be pop up with the following text:
- To download as image: Image download takes a long time, please wait. 
- To download as PDF: PDF download takes a long time, please wait.

2023-07-21 14:48 UTC, gionatta requested changes

2023-07-21 14:48 UTC, gionatta commented on superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx
> +          t('Image download takes a long time, please wait.'),
I think we can use a generic message to indicate a file is being prepared for download. The message would be the same for image and pdf.
Eg: "Preparing file for download, please wait."

2023-07-21 14:48 UTC, gionatta commented on superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx
> +          t('PDF download takes a long time, please wait.'),
See above comment.

2023-07-21 16:54 UTC, gionatta approved these changes

2023-07-27 20:06 UTC, gfieremans reviewed
Shouldn't this be for charts as well?

2023-07-27 20:11 UTC, gfieremans approved these changes

2023-07-28 12:42 UTC, EduardoSanday commented
> Shouldn't this be for charts as well?

Yes, I opened a separate story to do this implementation.
[NGLS-3279](https://jira.dev.global-intra.net:8443/browse/NGLS-3279)

2023-08-01 13:15 UTC, merged